// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface BedDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.BedDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bedId = 1 [json_name = "bedId"];</code>
   * @return The bedId.
   */
  int getBedId();

  /**
   * <code>string bedNo = 2 [json_name = "bedNo"];</code>
   * @return The bedNo.
   */
  java.lang.String getBedNo();
  /**
   * <code>string bedNo = 2 [json_name = "bedNo"];</code>
   * @return The bytes for bedNo.
   */
  com.google.protobuf.ByteString
      getBedNoBytes();

  /**
   * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
   * @return The deviceNo.
   */
  java.lang.String getDeviceNo();
  /**
   * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
   * @return The bytes for deviceNo.
   */
  com.google.protobuf.ByteString
      getDeviceNoBytes();

  /**
   * <code>string patientName = 4 [json_name = "patientName"];</code>
   * @return The patientName.
   */
  java.lang.String getPatientName();
  /**
   * <code>string patientName = 4 [json_name = "patientName"];</code>
   * @return The bytes for patientName.
   */
  com.google.protobuf.ByteString
      getPatientNameBytes();

  /**
   * <code>string patientGender = 5 [json_name = "patientGender"];</code>
   * @return The patientGender.
   */
  java.lang.String getPatientGender();
  /**
   * <code>string patientGender = 5 [json_name = "patientGender"];</code>
   * @return The bytes for patientGender.
   */
  com.google.protobuf.ByteString
      getPatientGenderBytes();

  /**
   * <code>int32 patientAge = 6 [json_name = "patientAge"];</code>
   * @return The patientAge.
   */
  int getPatientAge();

  /**
   * <code>string disease = 7 [json_name = "disease"];</code>
   * @return The disease.
   */
  java.lang.String getDisease();
  /**
   * <code>string disease = 7 [json_name = "disease"];</code>
   * @return The bytes for disease.
   */
  com.google.protobuf.ByteString
      getDiseaseBytes();
}
