// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

/**
 * Protobuf type {@code meta.v1.BedDetail}
 */
@com.google.protobuf.Generated
public final class BedDetail extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:meta.v1.BedDetail)
    BedDetailOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      BedDetail.class.getName());
  }
  // Use BedDetail.newBuilder() to construct.
  private BedDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BedDetail() {
    bedNo_ = "";
    deviceNo_ = "";
    patientName_ = "";
    patientGender_ = "";
    disease_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_BedDetail_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_BedDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.meta.v1.BedDetail.class, com.meta.v1.BedDetail.Builder.class);
  }

  public static final int BEDID_FIELD_NUMBER = 1;
  private int bedId_ = 0;
  /**
   * <code>int32 bedId = 1 [json_name = "bedId"];</code>
   * @return The bedId.
   */
  @java.lang.Override
  public int getBedId() {
    return bedId_;
  }

  public static final int BEDNO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bedNo_ = "";
  /**
   * <code>string bedNo = 2 [json_name = "bedNo"];</code>
   * @return The bedNo.
   */
  @java.lang.Override
  public java.lang.String getBedNo() {
    java.lang.Object ref = bedNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bedNo_ = s;
      return s;
    }
  }
  /**
   * <code>string bedNo = 2 [json_name = "bedNo"];</code>
   * @return The bytes for bedNo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBedNoBytes() {
    java.lang.Object ref = bedNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bedNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICENO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceNo_ = "";
  /**
   * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
   * @return The deviceNo.
   */
  @java.lang.Override
  public java.lang.String getDeviceNo() {
    java.lang.Object ref = deviceNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceNo_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
   * @return The bytes for deviceNo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceNoBytes() {
    java.lang.Object ref = deviceNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATIENTNAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object patientName_ = "";
  /**
   * <code>string patientName = 4 [json_name = "patientName"];</code>
   * @return The patientName.
   */
  @java.lang.Override
  public java.lang.String getPatientName() {
    java.lang.Object ref = patientName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patientName_ = s;
      return s;
    }
  }
  /**
   * <code>string patientName = 4 [json_name = "patientName"];</code>
   * @return The bytes for patientName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPatientNameBytes() {
    java.lang.Object ref = patientName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patientName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATIENTGENDER_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object patientGender_ = "";
  /**
   * <code>string patientGender = 5 [json_name = "patientGender"];</code>
   * @return The patientGender.
   */
  @java.lang.Override
  public java.lang.String getPatientGender() {
    java.lang.Object ref = patientGender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patientGender_ = s;
      return s;
    }
  }
  /**
   * <code>string patientGender = 5 [json_name = "patientGender"];</code>
   * @return The bytes for patientGender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPatientGenderBytes() {
    java.lang.Object ref = patientGender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patientGender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATIENTAGE_FIELD_NUMBER = 6;
  private int patientAge_ = 0;
  /**
   * <code>int32 patientAge = 6 [json_name = "patientAge"];</code>
   * @return The patientAge.
   */
  @java.lang.Override
  public int getPatientAge() {
    return patientAge_;
  }

  public static final int DISEASE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object disease_ = "";
  /**
   * <code>string disease = 7 [json_name = "disease"];</code>
   * @return The disease.
   */
  @java.lang.Override
  public java.lang.String getDisease() {
    java.lang.Object ref = disease_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      disease_ = s;
      return s;
    }
  }
  /**
   * <code>string disease = 7 [json_name = "disease"];</code>
   * @return The bytes for disease.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDiseaseBytes() {
    java.lang.Object ref = disease_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      disease_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bedId_ != 0) {
      output.writeInt32(1, bedId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bedNo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, bedNo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceNo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, deviceNo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(patientName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, patientName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(patientGender_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, patientGender_);
    }
    if (patientAge_ != 0) {
      output.writeInt32(6, patientAge_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(disease_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, disease_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bedId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, bedId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bedNo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, bedNo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceNo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, deviceNo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(patientName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, patientName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(patientGender_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, patientGender_);
    }
    if (patientAge_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, patientAge_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(disease_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, disease_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.meta.v1.BedDetail)) {
      return super.equals(obj);
    }
    com.meta.v1.BedDetail other = (com.meta.v1.BedDetail) obj;

    if (getBedId()
        != other.getBedId()) return false;
    if (!getBedNo()
        .equals(other.getBedNo())) return false;
    if (!getDeviceNo()
        .equals(other.getDeviceNo())) return false;
    if (!getPatientName()
        .equals(other.getPatientName())) return false;
    if (!getPatientGender()
        .equals(other.getPatientGender())) return false;
    if (getPatientAge()
        != other.getPatientAge()) return false;
    if (!getDisease()
        .equals(other.getDisease())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BEDID_FIELD_NUMBER;
    hash = (53 * hash) + getBedId();
    hash = (37 * hash) + BEDNO_FIELD_NUMBER;
    hash = (53 * hash) + getBedNo().hashCode();
    hash = (37 * hash) + DEVICENO_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceNo().hashCode();
    hash = (37 * hash) + PATIENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPatientName().hashCode();
    hash = (37 * hash) + PATIENTGENDER_FIELD_NUMBER;
    hash = (53 * hash) + getPatientGender().hashCode();
    hash = (37 * hash) + PATIENTAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPatientAge();
    hash = (37 * hash) + DISEASE_FIELD_NUMBER;
    hash = (53 * hash) + getDisease().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.meta.v1.BedDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.BedDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.BedDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.BedDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.BedDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.BedDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.BedDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.BedDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.meta.v1.BedDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.meta.v1.BedDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.meta.v1.BedDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.BedDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.meta.v1.BedDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meta.v1.BedDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.v1.BedDetail)
      com.meta.v1.BedDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_BedDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_BedDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meta.v1.BedDetail.class, com.meta.v1.BedDetail.Builder.class);
    }

    // Construct using com.meta.v1.BedDetail.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bedId_ = 0;
      bedNo_ = "";
      deviceNo_ = "";
      patientName_ = "";
      patientGender_ = "";
      patientAge_ = 0;
      disease_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_BedDetail_descriptor;
    }

    @java.lang.Override
    public com.meta.v1.BedDetail getDefaultInstanceForType() {
      return com.meta.v1.BedDetail.getDefaultInstance();
    }

    @java.lang.Override
    public com.meta.v1.BedDetail build() {
      com.meta.v1.BedDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.meta.v1.BedDetail buildPartial() {
      com.meta.v1.BedDetail result = new com.meta.v1.BedDetail(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.meta.v1.BedDetail result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bedId_ = bedId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bedNo_ = bedNo_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.deviceNo_ = deviceNo_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.patientName_ = patientName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.patientGender_ = patientGender_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.patientAge_ = patientAge_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.disease_ = disease_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.meta.v1.BedDetail) {
        return mergeFrom((com.meta.v1.BedDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.meta.v1.BedDetail other) {
      if (other == com.meta.v1.BedDetail.getDefaultInstance()) return this;
      if (other.getBedId() != 0) {
        setBedId(other.getBedId());
      }
      if (!other.getBedNo().isEmpty()) {
        bedNo_ = other.bedNo_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDeviceNo().isEmpty()) {
        deviceNo_ = other.deviceNo_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getPatientName().isEmpty()) {
        patientName_ = other.patientName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPatientGender().isEmpty()) {
        patientGender_ = other.patientGender_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getPatientAge() != 0) {
        setPatientAge(other.getPatientAge());
      }
      if (!other.getDisease().isEmpty()) {
        disease_ = other.disease_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bedId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              bedNo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              deviceNo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              patientName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              patientGender_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              patientAge_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              disease_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int bedId_ ;
    /**
     * <code>int32 bedId = 1 [json_name = "bedId"];</code>
     * @return The bedId.
     */
    @java.lang.Override
    public int getBedId() {
      return bedId_;
    }
    /**
     * <code>int32 bedId = 1 [json_name = "bedId"];</code>
     * @param value The bedId to set.
     * @return This builder for chaining.
     */
    public Builder setBedId(int value) {

      bedId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 bedId = 1 [json_name = "bedId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBedId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bedId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bedNo_ = "";
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @return The bedNo.
     */
    public java.lang.String getBedNo() {
      java.lang.Object ref = bedNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bedNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @return The bytes for bedNo.
     */
    public com.google.protobuf.ByteString
        getBedNoBytes() {
      java.lang.Object ref = bedNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bedNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @param value The bedNo to set.
     * @return This builder for chaining.
     */
    public Builder setBedNo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bedNo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBedNo() {
      bedNo_ = getDefaultInstance().getBedNo();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @param value The bytes for bedNo to set.
     * @return This builder for chaining.
     */
    public Builder setBedNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bedNo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object deviceNo_ = "";
    /**
     * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
     * @return The deviceNo.
     */
    public java.lang.String getDeviceNo() {
      java.lang.Object ref = deviceNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
     * @return The bytes for deviceNo.
     */
    public com.google.protobuf.ByteString
        getDeviceNoBytes() {
      java.lang.Object ref = deviceNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
     * @param value The deviceNo to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceNo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceNo_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceNo() {
      deviceNo_ = getDefaultInstance().getDeviceNo();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string deviceNo = 3 [json_name = "deviceNo"];</code>
     * @param value The bytes for deviceNo to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceNo_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object patientName_ = "";
    /**
     * <code>string patientName = 4 [json_name = "patientName"];</code>
     * @return The patientName.
     */
    public java.lang.String getPatientName() {
      java.lang.Object ref = patientName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patientName = 4 [json_name = "patientName"];</code>
     * @return The bytes for patientName.
     */
    public com.google.protobuf.ByteString
        getPatientNameBytes() {
      java.lang.Object ref = patientName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patientName = 4 [json_name = "patientName"];</code>
     * @param value The patientName to set.
     * @return This builder for chaining.
     */
    public Builder setPatientName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      patientName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string patientName = 4 [json_name = "patientName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPatientName() {
      patientName_ = getDefaultInstance().getPatientName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string patientName = 4 [json_name = "patientName"];</code>
     * @param value The bytes for patientName to set.
     * @return This builder for chaining.
     */
    public Builder setPatientNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      patientName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object patientGender_ = "";
    /**
     * <code>string patientGender = 5 [json_name = "patientGender"];</code>
     * @return The patientGender.
     */
    public java.lang.String getPatientGender() {
      java.lang.Object ref = patientGender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientGender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patientGender = 5 [json_name = "patientGender"];</code>
     * @return The bytes for patientGender.
     */
    public com.google.protobuf.ByteString
        getPatientGenderBytes() {
      java.lang.Object ref = patientGender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientGender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patientGender = 5 [json_name = "patientGender"];</code>
     * @param value The patientGender to set.
     * @return This builder for chaining.
     */
    public Builder setPatientGender(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      patientGender_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string patientGender = 5 [json_name = "patientGender"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPatientGender() {
      patientGender_ = getDefaultInstance().getPatientGender();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string patientGender = 5 [json_name = "patientGender"];</code>
     * @param value The bytes for patientGender to set.
     * @return This builder for chaining.
     */
    public Builder setPatientGenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      patientGender_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int patientAge_ ;
    /**
     * <code>int32 patientAge = 6 [json_name = "patientAge"];</code>
     * @return The patientAge.
     */
    @java.lang.Override
    public int getPatientAge() {
      return patientAge_;
    }
    /**
     * <code>int32 patientAge = 6 [json_name = "patientAge"];</code>
     * @param value The patientAge to set.
     * @return This builder for chaining.
     */
    public Builder setPatientAge(int value) {

      patientAge_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 patientAge = 6 [json_name = "patientAge"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPatientAge() {
      bitField0_ = (bitField0_ & ~0x00000020);
      patientAge_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object disease_ = "";
    /**
     * <code>string disease = 7 [json_name = "disease"];</code>
     * @return The disease.
     */
    public java.lang.String getDisease() {
      java.lang.Object ref = disease_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        disease_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string disease = 7 [json_name = "disease"];</code>
     * @return The bytes for disease.
     */
    public com.google.protobuf.ByteString
        getDiseaseBytes() {
      java.lang.Object ref = disease_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        disease_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string disease = 7 [json_name = "disease"];</code>
     * @param value The disease to set.
     * @return This builder for chaining.
     */
    public Builder setDisease(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      disease_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string disease = 7 [json_name = "disease"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDisease() {
      disease_ = getDefaultInstance().getDisease();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string disease = 7 [json_name = "disease"];</code>
     * @param value The bytes for disease to set.
     * @return This builder for chaining.
     */
    public Builder setDiseaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      disease_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:meta.v1.BedDetail)
  }

  // @@protoc_insertion_point(class_scope:meta.v1.BedDetail)
  private static final com.meta.v1.BedDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.meta.v1.BedDetail();
  }

  public static com.meta.v1.BedDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BedDetail>
      PARSER = new com.google.protobuf.AbstractParser<BedDetail>() {
    @java.lang.Override
    public BedDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BedDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BedDetail> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.meta.v1.BedDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

