// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface GetAlertsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.GetAlertsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 page = 1 [json_name = "page"];</code>
   * @return The page.
   */
  int getPage();

  /**
   * <code>int32 pageSize = 2 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  int getPageSize();

  /**
   * <code>int32 deptId = 3 [json_name = "deptId"];</code>
   * @return The deptId.
   */
  int getDeptId();
}
