// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface GetBedsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.GetBedsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  java.util.List<com.meta.v1.BedDetail> 
      getBedsList();
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  com.meta.v1.BedDetail getBeds(int index);
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  int getBedsCount();
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  java.util.List<? extends com.meta.v1.BedDetailOrBuilder> 
      getBedsOrBuilderList();
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  com.meta.v1.BedDetailOrBuilder getBedsOrBuilder(
      int index);
}
