// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

/**
 * Protobuf type {@code meta.v1.GetBedsResponse}
 */
@com.google.protobuf.Generated
public final class GetBedsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:meta.v1.GetBedsResponse)
    GetBedsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      GetBedsResponse.class.getName());
  }
  // Use GetBedsResponse.newBuilder() to construct.
  private GetBedsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetBedsResponse() {
    beds_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_GetBedsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_GetBedsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.meta.v1.GetBedsResponse.class, com.meta.v1.GetBedsResponse.Builder.class);
  }

  public static final int BEDS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.meta.v1.BedDetail> beds_;
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  @java.lang.Override
  public java.util.List<com.meta.v1.BedDetail> getBedsList() {
    return beds_;
  }
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.meta.v1.BedDetailOrBuilder> 
      getBedsOrBuilderList() {
    return beds_;
  }
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  @java.lang.Override
  public int getBedsCount() {
    return beds_.size();
  }
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  @java.lang.Override
  public com.meta.v1.BedDetail getBeds(int index) {
    return beds_.get(index);
  }
  /**
   * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
   */
  @java.lang.Override
  public com.meta.v1.BedDetailOrBuilder getBedsOrBuilder(
      int index) {
    return beds_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < beds_.size(); i++) {
      output.writeMessage(1, beds_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < beds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, beds_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.meta.v1.GetBedsResponse)) {
      return super.equals(obj);
    }
    com.meta.v1.GetBedsResponse other = (com.meta.v1.GetBedsResponse) obj;

    if (!getBedsList()
        .equals(other.getBedsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBedsCount() > 0) {
      hash = (37 * hash) + BEDS_FIELD_NUMBER;
      hash = (53 * hash) + getBedsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.meta.v1.GetBedsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.meta.v1.GetBedsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.meta.v1.GetBedsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.GetBedsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.meta.v1.GetBedsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meta.v1.GetBedsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.v1.GetBedsResponse)
      com.meta.v1.GetBedsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetBedsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetBedsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meta.v1.GetBedsResponse.class, com.meta.v1.GetBedsResponse.Builder.class);
    }

    // Construct using com.meta.v1.GetBedsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (bedsBuilder_ == null) {
        beds_ = java.util.Collections.emptyList();
      } else {
        beds_ = null;
        bedsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetBedsResponse_descriptor;
    }

    @java.lang.Override
    public com.meta.v1.GetBedsResponse getDefaultInstanceForType() {
      return com.meta.v1.GetBedsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.meta.v1.GetBedsResponse build() {
      com.meta.v1.GetBedsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.meta.v1.GetBedsResponse buildPartial() {
      com.meta.v1.GetBedsResponse result = new com.meta.v1.GetBedsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.meta.v1.GetBedsResponse result) {
      if (bedsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          beds_ = java.util.Collections.unmodifiableList(beds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.beds_ = beds_;
      } else {
        result.beds_ = bedsBuilder_.build();
      }
    }

    private void buildPartial0(com.meta.v1.GetBedsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.meta.v1.GetBedsResponse) {
        return mergeFrom((com.meta.v1.GetBedsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.meta.v1.GetBedsResponse other) {
      if (other == com.meta.v1.GetBedsResponse.getDefaultInstance()) return this;
      if (bedsBuilder_ == null) {
        if (!other.beds_.isEmpty()) {
          if (beds_.isEmpty()) {
            beds_ = other.beds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBedsIsMutable();
            beds_.addAll(other.beds_);
          }
          onChanged();
        }
      } else {
        if (!other.beds_.isEmpty()) {
          if (bedsBuilder_.isEmpty()) {
            bedsBuilder_.dispose();
            bedsBuilder_ = null;
            beds_ = other.beds_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bedsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetBedsFieldBuilder() : null;
          } else {
            bedsBuilder_.addAllMessages(other.beds_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.meta.v1.BedDetail m =
                  input.readMessage(
                      com.meta.v1.BedDetail.parser(),
                      extensionRegistry);
              if (bedsBuilder_ == null) {
                ensureBedsIsMutable();
                beds_.add(m);
              } else {
                bedsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.meta.v1.BedDetail> beds_ =
      java.util.Collections.emptyList();
    private void ensureBedsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        beds_ = new java.util.ArrayList<com.meta.v1.BedDetail>(beds_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.meta.v1.BedDetail, com.meta.v1.BedDetail.Builder, com.meta.v1.BedDetailOrBuilder> bedsBuilder_;

    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public java.util.List<com.meta.v1.BedDetail> getBedsList() {
      if (bedsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(beds_);
      } else {
        return bedsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public int getBedsCount() {
      if (bedsBuilder_ == null) {
        return beds_.size();
      } else {
        return bedsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public com.meta.v1.BedDetail getBeds(int index) {
      if (bedsBuilder_ == null) {
        return beds_.get(index);
      } else {
        return bedsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder setBeds(
        int index, com.meta.v1.BedDetail value) {
      if (bedsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBedsIsMutable();
        beds_.set(index, value);
        onChanged();
      } else {
        bedsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder setBeds(
        int index, com.meta.v1.BedDetail.Builder builderForValue) {
      if (bedsBuilder_ == null) {
        ensureBedsIsMutable();
        beds_.set(index, builderForValue.build());
        onChanged();
      } else {
        bedsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder addBeds(com.meta.v1.BedDetail value) {
      if (bedsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBedsIsMutable();
        beds_.add(value);
        onChanged();
      } else {
        bedsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder addBeds(
        int index, com.meta.v1.BedDetail value) {
      if (bedsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBedsIsMutable();
        beds_.add(index, value);
        onChanged();
      } else {
        bedsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder addBeds(
        com.meta.v1.BedDetail.Builder builderForValue) {
      if (bedsBuilder_ == null) {
        ensureBedsIsMutable();
        beds_.add(builderForValue.build());
        onChanged();
      } else {
        bedsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder addBeds(
        int index, com.meta.v1.BedDetail.Builder builderForValue) {
      if (bedsBuilder_ == null) {
        ensureBedsIsMutable();
        beds_.add(index, builderForValue.build());
        onChanged();
      } else {
        bedsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder addAllBeds(
        java.lang.Iterable<? extends com.meta.v1.BedDetail> values) {
      if (bedsBuilder_ == null) {
        ensureBedsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, beds_);
        onChanged();
      } else {
        bedsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder clearBeds() {
      if (bedsBuilder_ == null) {
        beds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bedsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public Builder removeBeds(int index) {
      if (bedsBuilder_ == null) {
        ensureBedsIsMutable();
        beds_.remove(index);
        onChanged();
      } else {
        bedsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public com.meta.v1.BedDetail.Builder getBedsBuilder(
        int index) {
      return internalGetBedsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public com.meta.v1.BedDetailOrBuilder getBedsOrBuilder(
        int index) {
      if (bedsBuilder_ == null) {
        return beds_.get(index);  } else {
        return bedsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public java.util.List<? extends com.meta.v1.BedDetailOrBuilder> 
         getBedsOrBuilderList() {
      if (bedsBuilder_ != null) {
        return bedsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(beds_);
      }
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public com.meta.v1.BedDetail.Builder addBedsBuilder() {
      return internalGetBedsFieldBuilder().addBuilder(
          com.meta.v1.BedDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public com.meta.v1.BedDetail.Builder addBedsBuilder(
        int index) {
      return internalGetBedsFieldBuilder().addBuilder(
          index, com.meta.v1.BedDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.v1.BedDetail beds = 1 [json_name = "beds"];</code>
     */
    public java.util.List<com.meta.v1.BedDetail.Builder> 
         getBedsBuilderList() {
      return internalGetBedsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.meta.v1.BedDetail, com.meta.v1.BedDetail.Builder, com.meta.v1.BedDetailOrBuilder> 
        internalGetBedsFieldBuilder() {
      if (bedsBuilder_ == null) {
        bedsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.meta.v1.BedDetail, com.meta.v1.BedDetail.Builder, com.meta.v1.BedDetailOrBuilder>(
                beds_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        beds_ = null;
      }
      return bedsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:meta.v1.GetBedsResponse)
  }

  // @@protoc_insertion_point(class_scope:meta.v1.GetBedsResponse)
  private static final com.meta.v1.GetBedsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.meta.v1.GetBedsResponse();
  }

  public static com.meta.v1.GetBedsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetBedsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetBedsResponse>() {
    @java.lang.Override
    public GetBedsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetBedsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetBedsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.meta.v1.GetBedsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

