// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface GetInfusionDevicesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.GetInfusionDevicesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  java.util.List<com.meta.v1.InfusionDeviceDetail> 
      getInfusionDevicesList();
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  com.meta.v1.InfusionDeviceDetail getInfusionDevices(int index);
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  int getInfusionDevicesCount();
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  java.util.List<? extends com.meta.v1.InfusionDeviceDetailOrBuilder> 
      getInfusionDevicesOrBuilderList();
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  com.meta.v1.InfusionDeviceDetailOrBuilder getInfusionDevicesOrBuilder(
      int index);
}
