// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface GetUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.GetUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.meta.v1.UserDetail user = 1 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.meta.v1.UserDetail user = 1 [json_name = "user"];</code>
   * @return The user.
   */
  com.meta.v1.UserDetail getUser();
  /**
   * <code>.meta.v1.UserDetail user = 1 [json_name = "user"];</code>
   */
  com.meta.v1.UserDetailOrBuilder getUserOrBuilder();
}
