// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface UserDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.UserDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  int getUserId();

  /**
   * <code>string userName = 2 [json_name = "userName"];</code>
   * @return The userName.
   */
  java.lang.String getUserName();
  /**
   * <code>string userName = 2 [json_name = "userName"];</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();

  /**
   * <code>string userRole = 3 [json_name = "userRole"];</code>
   * @return The userRole.
   */
  java.lang.String getUserRole();
  /**
   * <code>string userRole = 3 [json_name = "userRole"];</code>
   * @return The bytes for userRole.
   */
  com.google.protobuf.ByteString
      getUserRoleBytes();
}
