// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface AlertDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.AlertDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 alertId = 1 [json_name = "alertId"];</code>
   * @return The alertId.
   */
  int getAlertId();

  /**
   * <code>string bedNo = 2 [json_name = "bedNo"];</code>
   * @return The bedNo.
   */
  java.lang.String getBedNo();
  /**
   * <code>string bedNo = 2 [json_name = "bedNo"];</code>
   * @return The bytes for bedNo.
   */
  com.google.protobuf.ByteString
      getBedNoBytes();

  /**
   * <code>string alertType = 3 [json_name = "alertType"];</code>
   * @return The alertType.
   */
  java.lang.String getAlertType();
  /**
   * <code>string alertType = 3 [json_name = "alertType"];</code>
   * @return The bytes for alertType.
   */
  com.google.protobuf.ByteString
      getAlertTypeBytes();

  /**
   * <code>string alertTime = 4 [json_name = "alertTime"];</code>
   * @return The alertTime.
   */
  java.lang.String getAlertTime();
  /**
   * <code>string alertTime = 4 [json_name = "alertTime"];</code>
   * @return The bytes for alertTime.
   */
  com.google.protobuf.ByteString
      getAlertTimeBytes();
}
