// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

/**
 * Protobuf type {@code meta.v1.AlertDetail}
 */
@com.google.protobuf.Generated
public final class AlertDetail extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:meta.v1.AlertDetail)
    AlertDetailOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      AlertDetail.class.getName());
  }
  // Use AlertDetail.newBuilder() to construct.
  private AlertDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AlertDetail() {
    bedNo_ = "";
    alertType_ = "";
    alertTime_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_AlertDetail_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_AlertDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.meta.v1.AlertDetail.class, com.meta.v1.AlertDetail.Builder.class);
  }

  public static final int ALERTID_FIELD_NUMBER = 1;
  private int alertId_ = 0;
  /**
   * <code>int32 alertId = 1 [json_name = "alertId"];</code>
   * @return The alertId.
   */
  @java.lang.Override
  public int getAlertId() {
    return alertId_;
  }

  public static final int BEDNO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bedNo_ = "";
  /**
   * <code>string bedNo = 2 [json_name = "bedNo"];</code>
   * @return The bedNo.
   */
  @java.lang.Override
  public java.lang.String getBedNo() {
    java.lang.Object ref = bedNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bedNo_ = s;
      return s;
    }
  }
  /**
   * <code>string bedNo = 2 [json_name = "bedNo"];</code>
   * @return The bytes for bedNo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBedNoBytes() {
    java.lang.Object ref = bedNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bedNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALERTTYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alertType_ = "";
  /**
   * <code>string alertType = 3 [json_name = "alertType"];</code>
   * @return The alertType.
   */
  @java.lang.Override
  public java.lang.String getAlertType() {
    java.lang.Object ref = alertType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alertType_ = s;
      return s;
    }
  }
  /**
   * <code>string alertType = 3 [json_name = "alertType"];</code>
   * @return The bytes for alertType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlertTypeBytes() {
    java.lang.Object ref = alertType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alertType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALERTTIME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alertTime_ = "";
  /**
   * <code>string alertTime = 4 [json_name = "alertTime"];</code>
   * @return The alertTime.
   */
  @java.lang.Override
  public java.lang.String getAlertTime() {
    java.lang.Object ref = alertTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alertTime_ = s;
      return s;
    }
  }
  /**
   * <code>string alertTime = 4 [json_name = "alertTime"];</code>
   * @return The bytes for alertTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlertTimeBytes() {
    java.lang.Object ref = alertTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alertTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (alertId_ != 0) {
      output.writeInt32(1, alertId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bedNo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, bedNo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alertType_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, alertType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alertTime_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, alertTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (alertId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, alertId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bedNo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, bedNo_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alertType_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, alertType_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(alertTime_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, alertTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.meta.v1.AlertDetail)) {
      return super.equals(obj);
    }
    com.meta.v1.AlertDetail other = (com.meta.v1.AlertDetail) obj;

    if (getAlertId()
        != other.getAlertId()) return false;
    if (!getBedNo()
        .equals(other.getBedNo())) return false;
    if (!getAlertType()
        .equals(other.getAlertType())) return false;
    if (!getAlertTime()
        .equals(other.getAlertTime())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALERTID_FIELD_NUMBER;
    hash = (53 * hash) + getAlertId();
    hash = (37 * hash) + BEDNO_FIELD_NUMBER;
    hash = (53 * hash) + getBedNo().hashCode();
    hash = (37 * hash) + ALERTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAlertType().hashCode();
    hash = (37 * hash) + ALERTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getAlertTime().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.meta.v1.AlertDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.AlertDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.AlertDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.AlertDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.AlertDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.AlertDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.AlertDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.AlertDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.meta.v1.AlertDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.meta.v1.AlertDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.meta.v1.AlertDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.AlertDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.meta.v1.AlertDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meta.v1.AlertDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.v1.AlertDetail)
      com.meta.v1.AlertDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_AlertDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_AlertDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meta.v1.AlertDetail.class, com.meta.v1.AlertDetail.Builder.class);
    }

    // Construct using com.meta.v1.AlertDetail.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      alertId_ = 0;
      bedNo_ = "";
      alertType_ = "";
      alertTime_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_AlertDetail_descriptor;
    }

    @java.lang.Override
    public com.meta.v1.AlertDetail getDefaultInstanceForType() {
      return com.meta.v1.AlertDetail.getDefaultInstance();
    }

    @java.lang.Override
    public com.meta.v1.AlertDetail build() {
      com.meta.v1.AlertDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.meta.v1.AlertDetail buildPartial() {
      com.meta.v1.AlertDetail result = new com.meta.v1.AlertDetail(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.meta.v1.AlertDetail result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.alertId_ = alertId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bedNo_ = bedNo_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.alertType_ = alertType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.alertTime_ = alertTime_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.meta.v1.AlertDetail) {
        return mergeFrom((com.meta.v1.AlertDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.meta.v1.AlertDetail other) {
      if (other == com.meta.v1.AlertDetail.getDefaultInstance()) return this;
      if (other.getAlertId() != 0) {
        setAlertId(other.getAlertId());
      }
      if (!other.getBedNo().isEmpty()) {
        bedNo_ = other.bedNo_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getAlertType().isEmpty()) {
        alertType_ = other.alertType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAlertTime().isEmpty()) {
        alertTime_ = other.alertTime_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              alertId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              bedNo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              alertType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              alertTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int alertId_ ;
    /**
     * <code>int32 alertId = 1 [json_name = "alertId"];</code>
     * @return The alertId.
     */
    @java.lang.Override
    public int getAlertId() {
      return alertId_;
    }
    /**
     * <code>int32 alertId = 1 [json_name = "alertId"];</code>
     * @param value The alertId to set.
     * @return This builder for chaining.
     */
    public Builder setAlertId(int value) {

      alertId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 alertId = 1 [json_name = "alertId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      alertId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bedNo_ = "";
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @return The bedNo.
     */
    public java.lang.String getBedNo() {
      java.lang.Object ref = bedNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bedNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @return The bytes for bedNo.
     */
    public com.google.protobuf.ByteString
        getBedNoBytes() {
      java.lang.Object ref = bedNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bedNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @param value The bedNo to set.
     * @return This builder for chaining.
     */
    public Builder setBedNo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bedNo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBedNo() {
      bedNo_ = getDefaultInstance().getBedNo();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string bedNo = 2 [json_name = "bedNo"];</code>
     * @param value The bytes for bedNo to set.
     * @return This builder for chaining.
     */
    public Builder setBedNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bedNo_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object alertType_ = "";
    /**
     * <code>string alertType = 3 [json_name = "alertType"];</code>
     * @return The alertType.
     */
    public java.lang.String getAlertType() {
      java.lang.Object ref = alertType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alertType = 3 [json_name = "alertType"];</code>
     * @return The bytes for alertType.
     */
    public com.google.protobuf.ByteString
        getAlertTypeBytes() {
      java.lang.Object ref = alertType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alertType = 3 [json_name = "alertType"];</code>
     * @param value The alertType to set.
     * @return This builder for chaining.
     */
    public Builder setAlertType(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alertType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string alertType = 3 [json_name = "alertType"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertType() {
      alertType_ = getDefaultInstance().getAlertType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string alertType = 3 [json_name = "alertType"];</code>
     * @param value The bytes for alertType to set.
     * @return This builder for chaining.
     */
    public Builder setAlertTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alertType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object alertTime_ = "";
    /**
     * <code>string alertTime = 4 [json_name = "alertTime"];</code>
     * @return The alertTime.
     */
    public java.lang.String getAlertTime() {
      java.lang.Object ref = alertTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alertTime = 4 [json_name = "alertTime"];</code>
     * @return The bytes for alertTime.
     */
    public com.google.protobuf.ByteString
        getAlertTimeBytes() {
      java.lang.Object ref = alertTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alertTime = 4 [json_name = "alertTime"];</code>
     * @param value The alertTime to set.
     * @return This builder for chaining.
     */
    public Builder setAlertTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alertTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string alertTime = 4 [json_name = "alertTime"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlertTime() {
      alertTime_ = getDefaultInstance().getAlertTime();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string alertTime = 4 [json_name = "alertTime"];</code>
     * @param value The bytes for alertTime to set.
     * @return This builder for chaining.
     */
    public Builder setAlertTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alertTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:meta.v1.AlertDetail)
  }

  // @@protoc_insertion_point(class_scope:meta.v1.AlertDetail)
  private static final com.meta.v1.AlertDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.meta.v1.AlertDetail();
  }

  public static com.meta.v1.AlertDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AlertDetail>
      PARSER = new com.google.protobuf.AbstractParser<AlertDetail>() {
    @java.lang.Override
    public AlertDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AlertDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AlertDetail> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.meta.v1.AlertDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

