// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface AnalysisResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.AnalysisResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 入住人数
   * </pre>
   *
   * <code>int32 inBed = 1 [json_name = "inBed"];</code>
   * @return The inBed.
   */
  int getInBed();

  /**
   * <pre>
   * 空闲人数
   * </pre>
   *
   * <code>int32 freeBed = 2 [json_name = "freeBed"];</code>
   * @return The freeBed.
   */
  int getFreeBed();
}
