// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

/**
 * Protobuf type {@code meta.v1.AnalysisResponse}
 */
@com.google.protobuf.Generated
public final class AnalysisResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:meta.v1.AnalysisResponse)
    AnalysisResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      AnalysisResponse.class.getName());
  }
  // Use AnalysisResponse.newBuilder() to construct.
  private AnalysisResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AnalysisResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_AnalysisResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_AnalysisResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.meta.v1.AnalysisResponse.class, com.meta.v1.AnalysisResponse.Builder.class);
  }

  public static final int INBED_FIELD_NUMBER = 1;
  private int inBed_ = 0;
  /**
   * <pre>
   * 入住人数
   * </pre>
   *
   * <code>int32 inBed = 1 [json_name = "inBed"];</code>
   * @return The inBed.
   */
  @java.lang.Override
  public int getInBed() {
    return inBed_;
  }

  public static final int FREEBED_FIELD_NUMBER = 2;
  private int freeBed_ = 0;
  /**
   * <pre>
   * 空闲人数
   * </pre>
   *
   * <code>int32 freeBed = 2 [json_name = "freeBed"];</code>
   * @return The freeBed.
   */
  @java.lang.Override
  public int getFreeBed() {
    return freeBed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (inBed_ != 0) {
      output.writeInt32(1, inBed_);
    }
    if (freeBed_ != 0) {
      output.writeInt32(2, freeBed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (inBed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, inBed_);
    }
    if (freeBed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, freeBed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.meta.v1.AnalysisResponse)) {
      return super.equals(obj);
    }
    com.meta.v1.AnalysisResponse other = (com.meta.v1.AnalysisResponse) obj;

    if (getInBed()
        != other.getInBed()) return false;
    if (getFreeBed()
        != other.getFreeBed()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INBED_FIELD_NUMBER;
    hash = (53 * hash) + getInBed();
    hash = (37 * hash) + FREEBED_FIELD_NUMBER;
    hash = (53 * hash) + getFreeBed();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.meta.v1.AnalysisResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.meta.v1.AnalysisResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.meta.v1.AnalysisResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.AnalysisResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.meta.v1.AnalysisResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meta.v1.AnalysisResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.v1.AnalysisResponse)
      com.meta.v1.AnalysisResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_AnalysisResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_AnalysisResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meta.v1.AnalysisResponse.class, com.meta.v1.AnalysisResponse.Builder.class);
    }

    // Construct using com.meta.v1.AnalysisResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      inBed_ = 0;
      freeBed_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_AnalysisResponse_descriptor;
    }

    @java.lang.Override
    public com.meta.v1.AnalysisResponse getDefaultInstanceForType() {
      return com.meta.v1.AnalysisResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.meta.v1.AnalysisResponse build() {
      com.meta.v1.AnalysisResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.meta.v1.AnalysisResponse buildPartial() {
      com.meta.v1.AnalysisResponse result = new com.meta.v1.AnalysisResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.meta.v1.AnalysisResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.inBed_ = inBed_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.freeBed_ = freeBed_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.meta.v1.AnalysisResponse) {
        return mergeFrom((com.meta.v1.AnalysisResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.meta.v1.AnalysisResponse other) {
      if (other == com.meta.v1.AnalysisResponse.getDefaultInstance()) return this;
      if (other.getInBed() != 0) {
        setInBed(other.getInBed());
      }
      if (other.getFreeBed() != 0) {
        setFreeBed(other.getFreeBed());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              inBed_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              freeBed_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int inBed_ ;
    /**
     * <pre>
     * 入住人数
     * </pre>
     *
     * <code>int32 inBed = 1 [json_name = "inBed"];</code>
     * @return The inBed.
     */
    @java.lang.Override
    public int getInBed() {
      return inBed_;
    }
    /**
     * <pre>
     * 入住人数
     * </pre>
     *
     * <code>int32 inBed = 1 [json_name = "inBed"];</code>
     * @param value The inBed to set.
     * @return This builder for chaining.
     */
    public Builder setInBed(int value) {

      inBed_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 入住人数
     * </pre>
     *
     * <code>int32 inBed = 1 [json_name = "inBed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInBed() {
      bitField0_ = (bitField0_ & ~0x00000001);
      inBed_ = 0;
      onChanged();
      return this;
    }

    private int freeBed_ ;
    /**
     * <pre>
     * 空闲人数
     * </pre>
     *
     * <code>int32 freeBed = 2 [json_name = "freeBed"];</code>
     * @return The freeBed.
     */
    @java.lang.Override
    public int getFreeBed() {
      return freeBed_;
    }
    /**
     * <pre>
     * 空闲人数
     * </pre>
     *
     * <code>int32 freeBed = 2 [json_name = "freeBed"];</code>
     * @param value The freeBed to set.
     * @return This builder for chaining.
     */
    public Builder setFreeBed(int value) {

      freeBed_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 空闲人数
     * </pre>
     *
     * <code>int32 freeBed = 2 [json_name = "freeBed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFreeBed() {
      bitField0_ = (bitField0_ & ~0x00000002);
      freeBed_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:meta.v1.AnalysisResponse)
  }

  // @@protoc_insertion_point(class_scope:meta.v1.AnalysisResponse)
  private static final com.meta.v1.AnalysisResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.meta.v1.AnalysisResponse();
  }

  public static com.meta.v1.AnalysisResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnalysisResponse>
      PARSER = new com.google.protobuf.AbstractParser<AnalysisResponse>() {
    @java.lang.Override
    public AnalysisResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnalysisResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnalysisResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.meta.v1.AnalysisResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

