// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface AnalysisRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.AnalysisRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 deptId = 1 [json_name = "deptId"];</code>
   * @return The deptId.
   */
  int getDeptId();
}
