// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

/**
 * Protobuf type {@code meta.v1.DrugDetail}
 */
@com.google.protobuf.Generated
public final class DrugDetail extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:meta.v1.DrugDetail)
    DrugDetailOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      DrugDetail.class.getName());
  }
  // Use DrugDetail.newBuilder() to construct.
  private DrugDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DrugDetail() {
    drugName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_DrugDetail_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_DrugDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.meta.v1.DrugDetail.class, com.meta.v1.DrugDetail.Builder.class);
  }

  public static final int DRUGID_FIELD_NUMBER = 1;
  private int drugId_ = 0;
  /**
   * <code>int32 drugId = 1 [json_name = "drugId"];</code>
   * @return The drugId.
   */
  @java.lang.Override
  public int getDrugId() {
    return drugId_;
  }

  public static final int DRUGNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object drugName_ = "";
  /**
   * <code>string drugName = 2 [json_name = "drugName"];</code>
   * @return The drugName.
   */
  @java.lang.Override
  public java.lang.String getDrugName() {
    java.lang.Object ref = drugName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      drugName_ = s;
      return s;
    }
  }
  /**
   * <code>string drugName = 2 [json_name = "drugName"];</code>
   * @return The bytes for drugName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDrugNameBytes() {
    java.lang.Object ref = drugName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      drugName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (drugId_ != 0) {
      output.writeInt32(1, drugId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(drugName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, drugName_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (drugId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, drugId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(drugName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, drugName_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.meta.v1.DrugDetail)) {
      return super.equals(obj);
    }
    com.meta.v1.DrugDetail other = (com.meta.v1.DrugDetail) obj;

    if (getDrugId()
        != other.getDrugId()) return false;
    if (!getDrugName()
        .equals(other.getDrugName())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DRUGID_FIELD_NUMBER;
    hash = (53 * hash) + getDrugId();
    hash = (37 * hash) + DRUGNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDrugName().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.meta.v1.DrugDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.DrugDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.DrugDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.DrugDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.DrugDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.DrugDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.DrugDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.DrugDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.meta.v1.DrugDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.meta.v1.DrugDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.meta.v1.DrugDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.DrugDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.meta.v1.DrugDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meta.v1.DrugDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.v1.DrugDetail)
      com.meta.v1.DrugDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_DrugDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_DrugDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meta.v1.DrugDetail.class, com.meta.v1.DrugDetail.Builder.class);
    }

    // Construct using com.meta.v1.DrugDetail.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      drugId_ = 0;
      drugName_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_DrugDetail_descriptor;
    }

    @java.lang.Override
    public com.meta.v1.DrugDetail getDefaultInstanceForType() {
      return com.meta.v1.DrugDetail.getDefaultInstance();
    }

    @java.lang.Override
    public com.meta.v1.DrugDetail build() {
      com.meta.v1.DrugDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.meta.v1.DrugDetail buildPartial() {
      com.meta.v1.DrugDetail result = new com.meta.v1.DrugDetail(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.meta.v1.DrugDetail result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.drugId_ = drugId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.drugName_ = drugName_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.meta.v1.DrugDetail) {
        return mergeFrom((com.meta.v1.DrugDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.meta.v1.DrugDetail other) {
      if (other == com.meta.v1.DrugDetail.getDefaultInstance()) return this;
      if (other.getDrugId() != 0) {
        setDrugId(other.getDrugId());
      }
      if (!other.getDrugName().isEmpty()) {
        drugName_ = other.drugName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              drugId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              drugName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int drugId_ ;
    /**
     * <code>int32 drugId = 1 [json_name = "drugId"];</code>
     * @return The drugId.
     */
    @java.lang.Override
    public int getDrugId() {
      return drugId_;
    }
    /**
     * <code>int32 drugId = 1 [json_name = "drugId"];</code>
     * @param value The drugId to set.
     * @return This builder for chaining.
     */
    public Builder setDrugId(int value) {

      drugId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 drugId = 1 [json_name = "drugId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDrugId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      drugId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object drugName_ = "";
    /**
     * <code>string drugName = 2 [json_name = "drugName"];</code>
     * @return The drugName.
     */
    public java.lang.String getDrugName() {
      java.lang.Object ref = drugName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        drugName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string drugName = 2 [json_name = "drugName"];</code>
     * @return The bytes for drugName.
     */
    public com.google.protobuf.ByteString
        getDrugNameBytes() {
      java.lang.Object ref = drugName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        drugName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string drugName = 2 [json_name = "drugName"];</code>
     * @param value The drugName to set.
     * @return This builder for chaining.
     */
    public Builder setDrugName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      drugName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string drugName = 2 [json_name = "drugName"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDrugName() {
      drugName_ = getDefaultInstance().getDrugName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string drugName = 2 [json_name = "drugName"];</code>
     * @param value The bytes for drugName to set.
     * @return This builder for chaining.
     */
    public Builder setDrugNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      drugName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:meta.v1.DrugDetail)
  }

  // @@protoc_insertion_point(class_scope:meta.v1.DrugDetail)
  private static final com.meta.v1.DrugDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.meta.v1.DrugDetail();
  }

  public static com.meta.v1.DrugDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DrugDetail>
      PARSER = new com.google.protobuf.AbstractParser<DrugDetail>() {
    @java.lang.Override
    public DrugDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DrugDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DrugDetail> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.meta.v1.DrugDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

