// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface DrugDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.DrugDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 drugId = 1 [json_name = "drugId"];</code>
   * @return The drugId.
   */
  int getDrugId();

  /**
   * <code>string drugName = 2 [json_name = "drugName"];</code>
   * @return The drugName.
   */
  java.lang.String getDrugName();
  /**
   * <code>string drugName = 2 [json_name = "drugName"];</code>
   * @return The bytes for drugName.
   */
  com.google.protobuf.ByteString
      getDrugNameBytes();
}
