// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

/**
 * Protobuf type {@code meta.v1.GetAlertsResponse}
 */
@com.google.protobuf.Generated
public final class GetAlertsResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:meta.v1.GetAlertsResponse)
    GetAlertsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      GetAlertsResponse.class.getName());
  }
  // Use GetAlertsResponse.newBuilder() to construct.
  private GetAlertsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetAlertsResponse() {
    alerts_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_GetAlertsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_GetAlertsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.meta.v1.GetAlertsResponse.class, com.meta.v1.GetAlertsResponse.Builder.class);
  }

  public static final int ALERTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.meta.v1.AlertDetail> alerts_;
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  @java.lang.Override
  public java.util.List<com.meta.v1.AlertDetail> getAlertsList() {
    return alerts_;
  }
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.meta.v1.AlertDetailOrBuilder> 
      getAlertsOrBuilderList() {
    return alerts_;
  }
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  @java.lang.Override
  public int getAlertsCount() {
    return alerts_.size();
  }
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  @java.lang.Override
  public com.meta.v1.AlertDetail getAlerts(int index) {
    return alerts_.get(index);
  }
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  @java.lang.Override
  public com.meta.v1.AlertDetailOrBuilder getAlertsOrBuilder(
      int index) {
    return alerts_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < alerts_.size(); i++) {
      output.writeMessage(1, alerts_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < alerts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, alerts_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.meta.v1.GetAlertsResponse)) {
      return super.equals(obj);
    }
    com.meta.v1.GetAlertsResponse other = (com.meta.v1.GetAlertsResponse) obj;

    if (!getAlertsList()
        .equals(other.getAlertsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAlertsCount() > 0) {
      hash = (37 * hash) + ALERTS_FIELD_NUMBER;
      hash = (53 * hash) + getAlertsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.meta.v1.GetAlertsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.meta.v1.GetAlertsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.meta.v1.GetAlertsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.GetAlertsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.meta.v1.GetAlertsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meta.v1.GetAlertsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.v1.GetAlertsResponse)
      com.meta.v1.GetAlertsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetAlertsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetAlertsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meta.v1.GetAlertsResponse.class, com.meta.v1.GetAlertsResponse.Builder.class);
    }

    // Construct using com.meta.v1.GetAlertsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (alertsBuilder_ == null) {
        alerts_ = java.util.Collections.emptyList();
      } else {
        alerts_ = null;
        alertsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetAlertsResponse_descriptor;
    }

    @java.lang.Override
    public com.meta.v1.GetAlertsResponse getDefaultInstanceForType() {
      return com.meta.v1.GetAlertsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.meta.v1.GetAlertsResponse build() {
      com.meta.v1.GetAlertsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.meta.v1.GetAlertsResponse buildPartial() {
      com.meta.v1.GetAlertsResponse result = new com.meta.v1.GetAlertsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.meta.v1.GetAlertsResponse result) {
      if (alertsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          alerts_ = java.util.Collections.unmodifiableList(alerts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.alerts_ = alerts_;
      } else {
        result.alerts_ = alertsBuilder_.build();
      }
    }

    private void buildPartial0(com.meta.v1.GetAlertsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.meta.v1.GetAlertsResponse) {
        return mergeFrom((com.meta.v1.GetAlertsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.meta.v1.GetAlertsResponse other) {
      if (other == com.meta.v1.GetAlertsResponse.getDefaultInstance()) return this;
      if (alertsBuilder_ == null) {
        if (!other.alerts_.isEmpty()) {
          if (alerts_.isEmpty()) {
            alerts_ = other.alerts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAlertsIsMutable();
            alerts_.addAll(other.alerts_);
          }
          onChanged();
        }
      } else {
        if (!other.alerts_.isEmpty()) {
          if (alertsBuilder_.isEmpty()) {
            alertsBuilder_.dispose();
            alertsBuilder_ = null;
            alerts_ = other.alerts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            alertsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetAlertsFieldBuilder() : null;
          } else {
            alertsBuilder_.addAllMessages(other.alerts_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.meta.v1.AlertDetail m =
                  input.readMessage(
                      com.meta.v1.AlertDetail.parser(),
                      extensionRegistry);
              if (alertsBuilder_ == null) {
                ensureAlertsIsMutable();
                alerts_.add(m);
              } else {
                alertsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.meta.v1.AlertDetail> alerts_ =
      java.util.Collections.emptyList();
    private void ensureAlertsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        alerts_ = new java.util.ArrayList<com.meta.v1.AlertDetail>(alerts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.meta.v1.AlertDetail, com.meta.v1.AlertDetail.Builder, com.meta.v1.AlertDetailOrBuilder> alertsBuilder_;

    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public java.util.List<com.meta.v1.AlertDetail> getAlertsList() {
      if (alertsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(alerts_);
      } else {
        return alertsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public int getAlertsCount() {
      if (alertsBuilder_ == null) {
        return alerts_.size();
      } else {
        return alertsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public com.meta.v1.AlertDetail getAlerts(int index) {
      if (alertsBuilder_ == null) {
        return alerts_.get(index);
      } else {
        return alertsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder setAlerts(
        int index, com.meta.v1.AlertDetail value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.set(index, value);
        onChanged();
      } else {
        alertsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder setAlerts(
        int index, com.meta.v1.AlertDetail.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.set(index, builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder addAlerts(com.meta.v1.AlertDetail value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.add(value);
        onChanged();
      } else {
        alertsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder addAlerts(
        int index, com.meta.v1.AlertDetail value) {
      if (alertsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlertsIsMutable();
        alerts_.add(index, value);
        onChanged();
      } else {
        alertsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder addAlerts(
        com.meta.v1.AlertDetail.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.add(builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder addAlerts(
        int index, com.meta.v1.AlertDetail.Builder builderForValue) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.add(index, builderForValue.build());
        onChanged();
      } else {
        alertsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder addAllAlerts(
        java.lang.Iterable<? extends com.meta.v1.AlertDetail> values) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alerts_);
        onChanged();
      } else {
        alertsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder clearAlerts() {
      if (alertsBuilder_ == null) {
        alerts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        alertsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public Builder removeAlerts(int index) {
      if (alertsBuilder_ == null) {
        ensureAlertsIsMutable();
        alerts_.remove(index);
        onChanged();
      } else {
        alertsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public com.meta.v1.AlertDetail.Builder getAlertsBuilder(
        int index) {
      return internalGetAlertsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public com.meta.v1.AlertDetailOrBuilder getAlertsOrBuilder(
        int index) {
      if (alertsBuilder_ == null) {
        return alerts_.get(index);  } else {
        return alertsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public java.util.List<? extends com.meta.v1.AlertDetailOrBuilder> 
         getAlertsOrBuilderList() {
      if (alertsBuilder_ != null) {
        return alertsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(alerts_);
      }
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public com.meta.v1.AlertDetail.Builder addAlertsBuilder() {
      return internalGetAlertsFieldBuilder().addBuilder(
          com.meta.v1.AlertDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public com.meta.v1.AlertDetail.Builder addAlertsBuilder(
        int index) {
      return internalGetAlertsFieldBuilder().addBuilder(
          index, com.meta.v1.AlertDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
     */
    public java.util.List<com.meta.v1.AlertDetail.Builder> 
         getAlertsBuilderList() {
      return internalGetAlertsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.meta.v1.AlertDetail, com.meta.v1.AlertDetail.Builder, com.meta.v1.AlertDetailOrBuilder> 
        internalGetAlertsFieldBuilder() {
      if (alertsBuilder_ == null) {
        alertsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.meta.v1.AlertDetail, com.meta.v1.AlertDetail.Builder, com.meta.v1.AlertDetailOrBuilder>(
                alerts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        alerts_ = null;
      }
      return alertsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:meta.v1.GetAlertsResponse)
  }

  // @@protoc_insertion_point(class_scope:meta.v1.GetAlertsResponse)
  private static final com.meta.v1.GetAlertsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.meta.v1.GetAlertsResponse();
  }

  public static com.meta.v1.GetAlertsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAlertsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAlertsResponse>() {
    @java.lang.Override
    public GetAlertsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetAlertsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAlertsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.meta.v1.GetAlertsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

