// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface GetAlertsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.GetAlertsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  java.util.List<com.meta.v1.AlertDetail> 
      getAlertsList();
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  com.meta.v1.AlertDetail getAlerts(int index);
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  int getAlertsCount();
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  java.util.List<? extends com.meta.v1.AlertDetailOrBuilder> 
      getAlertsOrBuilderList();
  /**
   * <code>repeated .meta.v1.AlertDetail alerts = 1 [json_name = "alerts"];</code>
   */
  com.meta.v1.AlertDetailOrBuilder getAlertsOrBuilder(
      int index);
}
