// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

/**
 * Protobuf type {@code meta.v1.GetInfusionDevicesResponse}
 */
@com.google.protobuf.Generated
public final class GetInfusionDevicesResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:meta.v1.GetInfusionDevicesResponse)
    GetInfusionDevicesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      GetInfusionDevicesResponse.class.getName());
  }
  // Use GetInfusionDevicesResponse.newBuilder() to construct.
  private GetInfusionDevicesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetInfusionDevicesResponse() {
    infusionDevices_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_GetInfusionDevicesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_GetInfusionDevicesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.meta.v1.GetInfusionDevicesResponse.class, com.meta.v1.GetInfusionDevicesResponse.Builder.class);
  }

  public static final int INFUSIONDEVICES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.meta.v1.InfusionDeviceDetail> infusionDevices_;
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  @java.lang.Override
  public java.util.List<com.meta.v1.InfusionDeviceDetail> getInfusionDevicesList() {
    return infusionDevices_;
  }
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.meta.v1.InfusionDeviceDetailOrBuilder> 
      getInfusionDevicesOrBuilderList() {
    return infusionDevices_;
  }
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  @java.lang.Override
  public int getInfusionDevicesCount() {
    return infusionDevices_.size();
  }
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  @java.lang.Override
  public com.meta.v1.InfusionDeviceDetail getInfusionDevices(int index) {
    return infusionDevices_.get(index);
  }
  /**
   * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
   */
  @java.lang.Override
  public com.meta.v1.InfusionDeviceDetailOrBuilder getInfusionDevicesOrBuilder(
      int index) {
    return infusionDevices_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < infusionDevices_.size(); i++) {
      output.writeMessage(1, infusionDevices_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < infusionDevices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, infusionDevices_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.meta.v1.GetInfusionDevicesResponse)) {
      return super.equals(obj);
    }
    com.meta.v1.GetInfusionDevicesResponse other = (com.meta.v1.GetInfusionDevicesResponse) obj;

    if (!getInfusionDevicesList()
        .equals(other.getInfusionDevicesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInfusionDevicesCount() > 0) {
      hash = (37 * hash) + INFUSIONDEVICES_FIELD_NUMBER;
      hash = (53 * hash) + getInfusionDevicesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.meta.v1.GetInfusionDevicesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.meta.v1.GetInfusionDevicesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.GetInfusionDevicesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.meta.v1.GetInfusionDevicesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meta.v1.GetInfusionDevicesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.v1.GetInfusionDevicesResponse)
      com.meta.v1.GetInfusionDevicesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetInfusionDevicesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetInfusionDevicesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meta.v1.GetInfusionDevicesResponse.class, com.meta.v1.GetInfusionDevicesResponse.Builder.class);
    }

    // Construct using com.meta.v1.GetInfusionDevicesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (infusionDevicesBuilder_ == null) {
        infusionDevices_ = java.util.Collections.emptyList();
      } else {
        infusionDevices_ = null;
        infusionDevicesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_GetInfusionDevicesResponse_descriptor;
    }

    @java.lang.Override
    public com.meta.v1.GetInfusionDevicesResponse getDefaultInstanceForType() {
      return com.meta.v1.GetInfusionDevicesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.meta.v1.GetInfusionDevicesResponse build() {
      com.meta.v1.GetInfusionDevicesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.meta.v1.GetInfusionDevicesResponse buildPartial() {
      com.meta.v1.GetInfusionDevicesResponse result = new com.meta.v1.GetInfusionDevicesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.meta.v1.GetInfusionDevicesResponse result) {
      if (infusionDevicesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          infusionDevices_ = java.util.Collections.unmodifiableList(infusionDevices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.infusionDevices_ = infusionDevices_;
      } else {
        result.infusionDevices_ = infusionDevicesBuilder_.build();
      }
    }

    private void buildPartial0(com.meta.v1.GetInfusionDevicesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.meta.v1.GetInfusionDevicesResponse) {
        return mergeFrom((com.meta.v1.GetInfusionDevicesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.meta.v1.GetInfusionDevicesResponse other) {
      if (other == com.meta.v1.GetInfusionDevicesResponse.getDefaultInstance()) return this;
      if (infusionDevicesBuilder_ == null) {
        if (!other.infusionDevices_.isEmpty()) {
          if (infusionDevices_.isEmpty()) {
            infusionDevices_ = other.infusionDevices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInfusionDevicesIsMutable();
            infusionDevices_.addAll(other.infusionDevices_);
          }
          onChanged();
        }
      } else {
        if (!other.infusionDevices_.isEmpty()) {
          if (infusionDevicesBuilder_.isEmpty()) {
            infusionDevicesBuilder_.dispose();
            infusionDevicesBuilder_ = null;
            infusionDevices_ = other.infusionDevices_;
            bitField0_ = (bitField0_ & ~0x00000001);
            infusionDevicesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetInfusionDevicesFieldBuilder() : null;
          } else {
            infusionDevicesBuilder_.addAllMessages(other.infusionDevices_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.meta.v1.InfusionDeviceDetail m =
                  input.readMessage(
                      com.meta.v1.InfusionDeviceDetail.parser(),
                      extensionRegistry);
              if (infusionDevicesBuilder_ == null) {
                ensureInfusionDevicesIsMutable();
                infusionDevices_.add(m);
              } else {
                infusionDevicesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.meta.v1.InfusionDeviceDetail> infusionDevices_ =
      java.util.Collections.emptyList();
    private void ensureInfusionDevicesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        infusionDevices_ = new java.util.ArrayList<com.meta.v1.InfusionDeviceDetail>(infusionDevices_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.meta.v1.InfusionDeviceDetail, com.meta.v1.InfusionDeviceDetail.Builder, com.meta.v1.InfusionDeviceDetailOrBuilder> infusionDevicesBuilder_;

    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public java.util.List<com.meta.v1.InfusionDeviceDetail> getInfusionDevicesList() {
      if (infusionDevicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(infusionDevices_);
      } else {
        return infusionDevicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public int getInfusionDevicesCount() {
      if (infusionDevicesBuilder_ == null) {
        return infusionDevices_.size();
      } else {
        return infusionDevicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public com.meta.v1.InfusionDeviceDetail getInfusionDevices(int index) {
      if (infusionDevicesBuilder_ == null) {
        return infusionDevices_.get(index);
      } else {
        return infusionDevicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder setInfusionDevices(
        int index, com.meta.v1.InfusionDeviceDetail value) {
      if (infusionDevicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfusionDevicesIsMutable();
        infusionDevices_.set(index, value);
        onChanged();
      } else {
        infusionDevicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder setInfusionDevices(
        int index, com.meta.v1.InfusionDeviceDetail.Builder builderForValue) {
      if (infusionDevicesBuilder_ == null) {
        ensureInfusionDevicesIsMutable();
        infusionDevices_.set(index, builderForValue.build());
        onChanged();
      } else {
        infusionDevicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder addInfusionDevices(com.meta.v1.InfusionDeviceDetail value) {
      if (infusionDevicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfusionDevicesIsMutable();
        infusionDevices_.add(value);
        onChanged();
      } else {
        infusionDevicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder addInfusionDevices(
        int index, com.meta.v1.InfusionDeviceDetail value) {
      if (infusionDevicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInfusionDevicesIsMutable();
        infusionDevices_.add(index, value);
        onChanged();
      } else {
        infusionDevicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder addInfusionDevices(
        com.meta.v1.InfusionDeviceDetail.Builder builderForValue) {
      if (infusionDevicesBuilder_ == null) {
        ensureInfusionDevicesIsMutable();
        infusionDevices_.add(builderForValue.build());
        onChanged();
      } else {
        infusionDevicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder addInfusionDevices(
        int index, com.meta.v1.InfusionDeviceDetail.Builder builderForValue) {
      if (infusionDevicesBuilder_ == null) {
        ensureInfusionDevicesIsMutable();
        infusionDevices_.add(index, builderForValue.build());
        onChanged();
      } else {
        infusionDevicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder addAllInfusionDevices(
        java.lang.Iterable<? extends com.meta.v1.InfusionDeviceDetail> values) {
      if (infusionDevicesBuilder_ == null) {
        ensureInfusionDevicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, infusionDevices_);
        onChanged();
      } else {
        infusionDevicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder clearInfusionDevices() {
      if (infusionDevicesBuilder_ == null) {
        infusionDevices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        infusionDevicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public Builder removeInfusionDevices(int index) {
      if (infusionDevicesBuilder_ == null) {
        ensureInfusionDevicesIsMutable();
        infusionDevices_.remove(index);
        onChanged();
      } else {
        infusionDevicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public com.meta.v1.InfusionDeviceDetail.Builder getInfusionDevicesBuilder(
        int index) {
      return internalGetInfusionDevicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public com.meta.v1.InfusionDeviceDetailOrBuilder getInfusionDevicesOrBuilder(
        int index) {
      if (infusionDevicesBuilder_ == null) {
        return infusionDevices_.get(index);  } else {
        return infusionDevicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public java.util.List<? extends com.meta.v1.InfusionDeviceDetailOrBuilder> 
         getInfusionDevicesOrBuilderList() {
      if (infusionDevicesBuilder_ != null) {
        return infusionDevicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(infusionDevices_);
      }
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public com.meta.v1.InfusionDeviceDetail.Builder addInfusionDevicesBuilder() {
      return internalGetInfusionDevicesFieldBuilder().addBuilder(
          com.meta.v1.InfusionDeviceDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public com.meta.v1.InfusionDeviceDetail.Builder addInfusionDevicesBuilder(
        int index) {
      return internalGetInfusionDevicesFieldBuilder().addBuilder(
          index, com.meta.v1.InfusionDeviceDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.v1.InfusionDeviceDetail infusionDevices = 1 [json_name = "infusionDevices"];</code>
     */
    public java.util.List<com.meta.v1.InfusionDeviceDetail.Builder> 
         getInfusionDevicesBuilderList() {
      return internalGetInfusionDevicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.meta.v1.InfusionDeviceDetail, com.meta.v1.InfusionDeviceDetail.Builder, com.meta.v1.InfusionDeviceDetailOrBuilder> 
        internalGetInfusionDevicesFieldBuilder() {
      if (infusionDevicesBuilder_ == null) {
        infusionDevicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.meta.v1.InfusionDeviceDetail, com.meta.v1.InfusionDeviceDetail.Builder, com.meta.v1.InfusionDeviceDetailOrBuilder>(
                infusionDevices_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        infusionDevices_ = null;
      }
      return infusionDevicesBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:meta.v1.GetInfusionDevicesResponse)
  }

  // @@protoc_insertion_point(class_scope:meta.v1.GetInfusionDevicesResponse)
  private static final com.meta.v1.GetInfusionDevicesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.meta.v1.GetInfusionDevicesResponse();
  }

  public static com.meta.v1.GetInfusionDevicesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetInfusionDevicesResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetInfusionDevicesResponse>() {
    @java.lang.Override
    public GetInfusionDevicesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetInfusionDevicesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetInfusionDevicesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.meta.v1.GetInfusionDevicesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

