// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface GetUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.GetUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  int getUserId();
}
