// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

/**
 * Protobuf type {@code meta.v1.InfusionDeviceDetail}
 */
@com.google.protobuf.Generated
public final class InfusionDeviceDetail extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:meta.v1.InfusionDeviceDetail)
    InfusionDeviceDetailOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      InfusionDeviceDetail.class.getName());
  }
  // Use InfusionDeviceDetail.newBuilder() to construct.
  private InfusionDeviceDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InfusionDeviceDetail() {
    bedNo_ = "";
    drugs_ = java.util.Collections.emptyList();
    disease_ = "";
    infusionTime_ = "";
    infusionStatus_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_InfusionDeviceDetail_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.meta.v1.MetaProto.internal_static_meta_v1_InfusionDeviceDetail_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.meta.v1.InfusionDeviceDetail.class, com.meta.v1.InfusionDeviceDetail.Builder.class);
  }

  public static final int BEDNO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bedNo_ = "";
  /**
   * <code>string bedNo = 1 [json_name = "bedNo"];</code>
   * @return The bedNo.
   */
  @java.lang.Override
  public java.lang.String getBedNo() {
    java.lang.Object ref = bedNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bedNo_ = s;
      return s;
    }
  }
  /**
   * <code>string bedNo = 1 [json_name = "bedNo"];</code>
   * @return The bytes for bedNo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBedNoBytes() {
    java.lang.Object ref = bedNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bedNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DRUGS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.meta.v1.DrugDetail> drugs_;
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  @java.lang.Override
  public java.util.List<com.meta.v1.DrugDetail> getDrugsList() {
    return drugs_;
  }
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.meta.v1.DrugDetailOrBuilder> 
      getDrugsOrBuilderList() {
    return drugs_;
  }
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  @java.lang.Override
  public int getDrugsCount() {
    return drugs_.size();
  }
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  @java.lang.Override
  public com.meta.v1.DrugDetail getDrugs(int index) {
    return drugs_.get(index);
  }
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  @java.lang.Override
  public com.meta.v1.DrugDetailOrBuilder getDrugsOrBuilder(
      int index) {
    return drugs_.get(index);
  }

  public static final int DISEASE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object disease_ = "";
  /**
   * <code>string disease = 3 [json_name = "disease"];</code>
   * @return The disease.
   */
  @java.lang.Override
  public java.lang.String getDisease() {
    java.lang.Object ref = disease_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      disease_ = s;
      return s;
    }
  }
  /**
   * <code>string disease = 3 [json_name = "disease"];</code>
   * @return The bytes for disease.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDiseaseBytes() {
    java.lang.Object ref = disease_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      disease_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INFUSIONTIME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object infusionTime_ = "";
  /**
   * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
   * @return The infusionTime.
   */
  @java.lang.Override
  public java.lang.String getInfusionTime() {
    java.lang.Object ref = infusionTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      infusionTime_ = s;
      return s;
    }
  }
  /**
   * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
   * @return The bytes for infusionTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInfusionTimeBytes() {
    java.lang.Object ref = infusionTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      infusionTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INFUSIONSTATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object infusionStatus_ = "";
  /**
   * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
   * @return The infusionStatus.
   */
  @java.lang.Override
  public java.lang.String getInfusionStatus() {
    java.lang.Object ref = infusionStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      infusionStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
   * @return The bytes for infusionStatus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInfusionStatusBytes() {
    java.lang.Object ref = infusionStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      infusionStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bedNo_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, bedNo_);
    }
    for (int i = 0; i < drugs_.size(); i++) {
      output.writeMessage(2, drugs_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(disease_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, disease_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(infusionTime_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, infusionTime_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(infusionStatus_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, infusionStatus_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bedNo_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, bedNo_);
    }
    for (int i = 0; i < drugs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, drugs_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(disease_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, disease_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(infusionTime_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, infusionTime_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(infusionStatus_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, infusionStatus_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.meta.v1.InfusionDeviceDetail)) {
      return super.equals(obj);
    }
    com.meta.v1.InfusionDeviceDetail other = (com.meta.v1.InfusionDeviceDetail) obj;

    if (!getBedNo()
        .equals(other.getBedNo())) return false;
    if (!getDrugsList()
        .equals(other.getDrugsList())) return false;
    if (!getDisease()
        .equals(other.getDisease())) return false;
    if (!getInfusionTime()
        .equals(other.getInfusionTime())) return false;
    if (!getInfusionStatus()
        .equals(other.getInfusionStatus())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BEDNO_FIELD_NUMBER;
    hash = (53 * hash) + getBedNo().hashCode();
    if (getDrugsCount() > 0) {
      hash = (37 * hash) + DRUGS_FIELD_NUMBER;
      hash = (53 * hash) + getDrugsList().hashCode();
    }
    hash = (37 * hash) + DISEASE_FIELD_NUMBER;
    hash = (53 * hash) + getDisease().hashCode();
    hash = (37 * hash) + INFUSIONTIME_FIELD_NUMBER;
    hash = (53 * hash) + getInfusionTime().hashCode();
    hash = (37 * hash) + INFUSIONSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getInfusionStatus().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.meta.v1.InfusionDeviceDetail parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.meta.v1.InfusionDeviceDetail parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.meta.v1.InfusionDeviceDetail parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.meta.v1.InfusionDeviceDetail parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.meta.v1.InfusionDeviceDetail prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meta.v1.InfusionDeviceDetail}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meta.v1.InfusionDeviceDetail)
      com.meta.v1.InfusionDeviceDetailOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_InfusionDeviceDetail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_InfusionDeviceDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.meta.v1.InfusionDeviceDetail.class, com.meta.v1.InfusionDeviceDetail.Builder.class);
    }

    // Construct using com.meta.v1.InfusionDeviceDetail.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bedNo_ = "";
      if (drugsBuilder_ == null) {
        drugs_ = java.util.Collections.emptyList();
      } else {
        drugs_ = null;
        drugsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      disease_ = "";
      infusionTime_ = "";
      infusionStatus_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.meta.v1.MetaProto.internal_static_meta_v1_InfusionDeviceDetail_descriptor;
    }

    @java.lang.Override
    public com.meta.v1.InfusionDeviceDetail getDefaultInstanceForType() {
      return com.meta.v1.InfusionDeviceDetail.getDefaultInstance();
    }

    @java.lang.Override
    public com.meta.v1.InfusionDeviceDetail build() {
      com.meta.v1.InfusionDeviceDetail result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.meta.v1.InfusionDeviceDetail buildPartial() {
      com.meta.v1.InfusionDeviceDetail result = new com.meta.v1.InfusionDeviceDetail(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.meta.v1.InfusionDeviceDetail result) {
      if (drugsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          drugs_ = java.util.Collections.unmodifiableList(drugs_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.drugs_ = drugs_;
      } else {
        result.drugs_ = drugsBuilder_.build();
      }
    }

    private void buildPartial0(com.meta.v1.InfusionDeviceDetail result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bedNo_ = bedNo_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.disease_ = disease_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.infusionTime_ = infusionTime_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.infusionStatus_ = infusionStatus_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.meta.v1.InfusionDeviceDetail) {
        return mergeFrom((com.meta.v1.InfusionDeviceDetail)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.meta.v1.InfusionDeviceDetail other) {
      if (other == com.meta.v1.InfusionDeviceDetail.getDefaultInstance()) return this;
      if (!other.getBedNo().isEmpty()) {
        bedNo_ = other.bedNo_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (drugsBuilder_ == null) {
        if (!other.drugs_.isEmpty()) {
          if (drugs_.isEmpty()) {
            drugs_ = other.drugs_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureDrugsIsMutable();
            drugs_.addAll(other.drugs_);
          }
          onChanged();
        }
      } else {
        if (!other.drugs_.isEmpty()) {
          if (drugsBuilder_.isEmpty()) {
            drugsBuilder_.dispose();
            drugsBuilder_ = null;
            drugs_ = other.drugs_;
            bitField0_ = (bitField0_ & ~0x00000002);
            drugsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetDrugsFieldBuilder() : null;
          } else {
            drugsBuilder_.addAllMessages(other.drugs_);
          }
        }
      }
      if (!other.getDisease().isEmpty()) {
        disease_ = other.disease_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getInfusionTime().isEmpty()) {
        infusionTime_ = other.infusionTime_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getInfusionStatus().isEmpty()) {
        infusionStatus_ = other.infusionStatus_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bedNo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              com.meta.v1.DrugDetail m =
                  input.readMessage(
                      com.meta.v1.DrugDetail.parser(),
                      extensionRegistry);
              if (drugsBuilder_ == null) {
                ensureDrugsIsMutable();
                drugs_.add(m);
              } else {
                drugsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              disease_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              infusionTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              infusionStatus_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object bedNo_ = "";
    /**
     * <code>string bedNo = 1 [json_name = "bedNo"];</code>
     * @return The bedNo.
     */
    public java.lang.String getBedNo() {
      java.lang.Object ref = bedNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bedNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bedNo = 1 [json_name = "bedNo"];</code>
     * @return The bytes for bedNo.
     */
    public com.google.protobuf.ByteString
        getBedNoBytes() {
      java.lang.Object ref = bedNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bedNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bedNo = 1 [json_name = "bedNo"];</code>
     * @param value The bedNo to set.
     * @return This builder for chaining.
     */
    public Builder setBedNo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bedNo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string bedNo = 1 [json_name = "bedNo"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBedNo() {
      bedNo_ = getDefaultInstance().getBedNo();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string bedNo = 1 [json_name = "bedNo"];</code>
     * @param value The bytes for bedNo to set.
     * @return This builder for chaining.
     */
    public Builder setBedNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bedNo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<com.meta.v1.DrugDetail> drugs_ =
      java.util.Collections.emptyList();
    private void ensureDrugsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        drugs_ = new java.util.ArrayList<com.meta.v1.DrugDetail>(drugs_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.meta.v1.DrugDetail, com.meta.v1.DrugDetail.Builder, com.meta.v1.DrugDetailOrBuilder> drugsBuilder_;

    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public java.util.List<com.meta.v1.DrugDetail> getDrugsList() {
      if (drugsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(drugs_);
      } else {
        return drugsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public int getDrugsCount() {
      if (drugsBuilder_ == null) {
        return drugs_.size();
      } else {
        return drugsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public com.meta.v1.DrugDetail getDrugs(int index) {
      if (drugsBuilder_ == null) {
        return drugs_.get(index);
      } else {
        return drugsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder setDrugs(
        int index, com.meta.v1.DrugDetail value) {
      if (drugsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDrugsIsMutable();
        drugs_.set(index, value);
        onChanged();
      } else {
        drugsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder setDrugs(
        int index, com.meta.v1.DrugDetail.Builder builderForValue) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        drugs_.set(index, builderForValue.build());
        onChanged();
      } else {
        drugsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder addDrugs(com.meta.v1.DrugDetail value) {
      if (drugsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDrugsIsMutable();
        drugs_.add(value);
        onChanged();
      } else {
        drugsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder addDrugs(
        int index, com.meta.v1.DrugDetail value) {
      if (drugsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDrugsIsMutable();
        drugs_.add(index, value);
        onChanged();
      } else {
        drugsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder addDrugs(
        com.meta.v1.DrugDetail.Builder builderForValue) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        drugs_.add(builderForValue.build());
        onChanged();
      } else {
        drugsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder addDrugs(
        int index, com.meta.v1.DrugDetail.Builder builderForValue) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        drugs_.add(index, builderForValue.build());
        onChanged();
      } else {
        drugsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder addAllDrugs(
        java.lang.Iterable<? extends com.meta.v1.DrugDetail> values) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, drugs_);
        onChanged();
      } else {
        drugsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder clearDrugs() {
      if (drugsBuilder_ == null) {
        drugs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        drugsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public Builder removeDrugs(int index) {
      if (drugsBuilder_ == null) {
        ensureDrugsIsMutable();
        drugs_.remove(index);
        onChanged();
      } else {
        drugsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public com.meta.v1.DrugDetail.Builder getDrugsBuilder(
        int index) {
      return internalGetDrugsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public com.meta.v1.DrugDetailOrBuilder getDrugsOrBuilder(
        int index) {
      if (drugsBuilder_ == null) {
        return drugs_.get(index);  } else {
        return drugsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public java.util.List<? extends com.meta.v1.DrugDetailOrBuilder> 
         getDrugsOrBuilderList() {
      if (drugsBuilder_ != null) {
        return drugsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(drugs_);
      }
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public com.meta.v1.DrugDetail.Builder addDrugsBuilder() {
      return internalGetDrugsFieldBuilder().addBuilder(
          com.meta.v1.DrugDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public com.meta.v1.DrugDetail.Builder addDrugsBuilder(
        int index) {
      return internalGetDrugsFieldBuilder().addBuilder(
          index, com.meta.v1.DrugDetail.getDefaultInstance());
    }
    /**
     * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
     */
    public java.util.List<com.meta.v1.DrugDetail.Builder> 
         getDrugsBuilderList() {
      return internalGetDrugsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.meta.v1.DrugDetail, com.meta.v1.DrugDetail.Builder, com.meta.v1.DrugDetailOrBuilder> 
        internalGetDrugsFieldBuilder() {
      if (drugsBuilder_ == null) {
        drugsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.meta.v1.DrugDetail, com.meta.v1.DrugDetail.Builder, com.meta.v1.DrugDetailOrBuilder>(
                drugs_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        drugs_ = null;
      }
      return drugsBuilder_;
    }

    private java.lang.Object disease_ = "";
    /**
     * <code>string disease = 3 [json_name = "disease"];</code>
     * @return The disease.
     */
    public java.lang.String getDisease() {
      java.lang.Object ref = disease_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        disease_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string disease = 3 [json_name = "disease"];</code>
     * @return The bytes for disease.
     */
    public com.google.protobuf.ByteString
        getDiseaseBytes() {
      java.lang.Object ref = disease_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        disease_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string disease = 3 [json_name = "disease"];</code>
     * @param value The disease to set.
     * @return This builder for chaining.
     */
    public Builder setDisease(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      disease_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string disease = 3 [json_name = "disease"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDisease() {
      disease_ = getDefaultInstance().getDisease();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string disease = 3 [json_name = "disease"];</code>
     * @param value The bytes for disease to set.
     * @return This builder for chaining.
     */
    public Builder setDiseaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      disease_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object infusionTime_ = "";
    /**
     * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
     * @return The infusionTime.
     */
    public java.lang.String getInfusionTime() {
      java.lang.Object ref = infusionTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        infusionTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
     * @return The bytes for infusionTime.
     */
    public com.google.protobuf.ByteString
        getInfusionTimeBytes() {
      java.lang.Object ref = infusionTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        infusionTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
     * @param value The infusionTime to set.
     * @return This builder for chaining.
     */
    public Builder setInfusionTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      infusionTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInfusionTime() {
      infusionTime_ = getDefaultInstance().getInfusionTime();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
     * @param value The bytes for infusionTime to set.
     * @return This builder for chaining.
     */
    public Builder setInfusionTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      infusionTime_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object infusionStatus_ = "";
    /**
     * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
     * @return The infusionStatus.
     */
    public java.lang.String getInfusionStatus() {
      java.lang.Object ref = infusionStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        infusionStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
     * @return The bytes for infusionStatus.
     */
    public com.google.protobuf.ByteString
        getInfusionStatusBytes() {
      java.lang.Object ref = infusionStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        infusionStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
     * @param value The infusionStatus to set.
     * @return This builder for chaining.
     */
    public Builder setInfusionStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      infusionStatus_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInfusionStatus() {
      infusionStatus_ = getDefaultInstance().getInfusionStatus();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
     * @param value The bytes for infusionStatus to set.
     * @return This builder for chaining.
     */
    public Builder setInfusionStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      infusionStatus_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:meta.v1.InfusionDeviceDetail)
  }

  // @@protoc_insertion_point(class_scope:meta.v1.InfusionDeviceDetail)
  private static final com.meta.v1.InfusionDeviceDetail DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.meta.v1.InfusionDeviceDetail();
  }

  public static com.meta.v1.InfusionDeviceDetail getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfusionDeviceDetail>
      PARSER = new com.google.protobuf.AbstractParser<InfusionDeviceDetail>() {
    @java.lang.Override
    public InfusionDeviceDetail parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InfusionDeviceDetail> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfusionDeviceDetail> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.meta.v1.InfusionDeviceDetail getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

