// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public interface InfusionDeviceDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meta.v1.InfusionDeviceDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bedNo = 1 [json_name = "bedNo"];</code>
   * @return The bedNo.
   */
  java.lang.String getBedNo();
  /**
   * <code>string bedNo = 1 [json_name = "bedNo"];</code>
   * @return The bytes for bedNo.
   */
  com.google.protobuf.ByteString
      getBedNoBytes();

  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  java.util.List<com.meta.v1.DrugDetail> 
      getDrugsList();
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  com.meta.v1.DrugDetail getDrugs(int index);
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  int getDrugsCount();
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  java.util.List<? extends com.meta.v1.DrugDetailOrBuilder> 
      getDrugsOrBuilderList();
  /**
   * <code>repeated .meta.v1.DrugDetail drugs = 2 [json_name = "drugs"];</code>
   */
  com.meta.v1.DrugDetailOrBuilder getDrugsOrBuilder(
      int index);

  /**
   * <code>string disease = 3 [json_name = "disease"];</code>
   * @return The disease.
   */
  java.lang.String getDisease();
  /**
   * <code>string disease = 3 [json_name = "disease"];</code>
   * @return The bytes for disease.
   */
  com.google.protobuf.ByteString
      getDiseaseBytes();

  /**
   * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
   * @return The infusionTime.
   */
  java.lang.String getInfusionTime();
  /**
   * <code>string infusionTime = 4 [json_name = "infusionTime"];</code>
   * @return The bytes for infusionTime.
   */
  com.google.protobuf.ByteString
      getInfusionTimeBytes();

  /**
   * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
   * @return The infusionStatus.
   */
  java.lang.String getInfusionStatus();
  /**
   * <code>string infusionStatus = 5 [json_name = "infusionStatus"];</code>
   * @return The bytes for infusionStatus.
   */
  com.google.protobuf.ByteString
      getInfusionStatusBytes();
}
