// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/meta/v1/meta.proto
// Protobuf Java Version: 4.31.1

package com.meta.v1;

@com.google.protobuf.Generated
public final class MetaProto {
  private MetaProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      MetaProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_GetBedsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_GetBedsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_GetBedsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_GetBedsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_BedDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_BedDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_GetAlertsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_GetAlertsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_GetAlertsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_GetAlertsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_AlertDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_AlertDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_GetInfusionDevicesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_GetInfusionDevicesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_GetInfusionDevicesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_GetInfusionDevicesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_InfusionDeviceDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_InfusionDeviceDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_DrugDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_DrugDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_GetUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_GetUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_GetUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_GetUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meta_v1_UserDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_meta_v1_UserDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/meta/v1/meta.proto\022\007meta.v1\"X\n\016G" +
      "etBedsRequest\022\022\n\004page\030\001 \001(\005R\004page\022\032\n\010pag" +
      "eSize\030\002 \001(\005R\010pageSize\022\026\n\006deptId\030\003 \001(\005R\006d" +
      "eptId\"9\n\017GetBedsResponse\022&\n\004beds\030\001 \003(\0132\022" +
      ".meta.v1.BedDetailR\004beds\"\321\001\n\tBedDetail\022\024" +
      "\n\005bedId\030\001 \001(\005R\005bedId\022\024\n\005bedNo\030\002 \001(\tR\005bed" +
      "No\022 \n\013patientName\030\003 \001(\tR\013patientName\022$\n\r" +
      "patientGender\030\004 \001(\tR\rpatientGender\022\036\n\npa" +
      "tientAge\030\005 \001(\005R\npatientAge\022\030\n\007disease\030\006 " +
      "\001(\tR\007disease\022\026\n\006status\030\007 \001(\tR\006status\"Z\n\020" +
      "GetAlertsRequest\022\022\n\004page\030\001 \001(\005R\004page\022\032\n\010" +
      "pageSize\030\002 \001(\005R\010pageSize\022\026\n\006deptId\030\003 \001(\005" +
      "R\006deptId\"A\n\021GetAlertsResponse\022,\n\006alerts\030" +
      "\001 \003(\0132\024.meta.v1.AlertDetailR\006alerts\"y\n\013A" +
      "lertDetail\022\030\n\007alertId\030\001 \001(\005R\007alertId\022\024\n\005" +
      "bedNo\030\002 \001(\tR\005bedNo\022\034\n\talertType\030\003 \001(\tR\ta" +
      "lertType\022\034\n\talertTime\030\004 \001(\tR\talertTime\"c" +
      "\n\031GetInfusionDevicesRequest\022\022\n\004page\030\001 \001(" +
      "\005R\004page\022\032\n\010pageSize\030\002 \001(\005R\010pageSize\022\026\n\006d" +
      "eptId\030\003 \001(\005R\006deptId\"e\n\032GetInfusionDevice" +
      "sResponse\022G\n\017infusionDevices\030\001 \003(\0132\035.met" +
      "a.v1.InfusionDeviceDetailR\017infusionDevic" +
      "es\"\275\001\n\024InfusionDeviceDetail\022\024\n\005bedNo\030\001 \001" +
      "(\tR\005bedNo\022)\n\005drugs\030\002 \003(\0132\023.meta.v1.DrugD" +
      "etailR\005drugs\022\030\n\007disease\030\003 \001(\tR\007disease\022\"" +
      "\n\014infusionTime\030\004 \001(\tR\014infusionTime\022&\n\016in" +
      "fusionStatus\030\005 \001(\tR\016infusionStatus\"@\n\nDr" +
      "ugDetail\022\026\n\006drugId\030\001 \001(\005R\006drugId\022\032\n\010drug" +
      "Name\030\002 \001(\tR\010drugName\"(\n\016GetUserRequest\022\026" +
      "\n\006userId\030\001 \001(\005R\006userId\":\n\017GetUserRespons" +
      "e\022\'\n\004user\030\001 \001(\0132\023.meta.v1.UserDetailR\004us" +
      "er\"\\\n\nUserDetail\022\026\n\006userId\030\001 \001(\005R\006userId" +
      "\022\032\n\010userName\030\002 \001(\tR\010userName\022\032\n\010userRole" +
      "\030\003 \001(\tR\010userRole2\264\002\n\013MetaService\022>\n\007GetU" +
      "ser\022\027.meta.v1.GetUserRequest\032\030.meta.v1.G" +
      "etUserResponse\"\000\022>\n\007GetBeds\022\027.meta.v1.Ge" +
      "tBedsRequest\032\030.meta.v1.GetBedsResponse\"\000" +
      "\022D\n\tGetAlerts\022\031.meta.v1.GetAlertsRequest" +
      "\032\032.meta.v1.GetAlertsResponse\"\000\022_\n\022GetInf" +
      "usionDevices\022\".meta.v1.GetInfusionDevice" +
      "sRequest\032#.meta.v1.GetInfusionDevicesRes" +
      "ponse\"\000B\201\001\n\013com.meta.v1B\tMetaProtoP\001Z*gi" +
      "thub.com/jahjah/edge-sight-go-sdk;metav1" +
      "\242\002\003MXX\252\002\007Meta.V1\312\002\007Meta\\V1\342\002\023Meta\\V1\\GPB" +
      "Metadata\352\002\010Meta::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_meta_v1_GetBedsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meta_v1_GetBedsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_GetBedsRequest_descriptor,
        new java.lang.String[] { "Page", "PageSize", "DeptId", });
    internal_static_meta_v1_GetBedsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meta_v1_GetBedsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_GetBedsResponse_descriptor,
        new java.lang.String[] { "Beds", });
    internal_static_meta_v1_BedDetail_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_meta_v1_BedDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_BedDetail_descriptor,
        new java.lang.String[] { "BedId", "BedNo", "PatientName", "PatientGender", "PatientAge", "Disease", "Status", });
    internal_static_meta_v1_GetAlertsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_meta_v1_GetAlertsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_GetAlertsRequest_descriptor,
        new java.lang.String[] { "Page", "PageSize", "DeptId", });
    internal_static_meta_v1_GetAlertsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_meta_v1_GetAlertsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_GetAlertsResponse_descriptor,
        new java.lang.String[] { "Alerts", });
    internal_static_meta_v1_AlertDetail_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_meta_v1_AlertDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_AlertDetail_descriptor,
        new java.lang.String[] { "AlertId", "BedNo", "AlertType", "AlertTime", });
    internal_static_meta_v1_GetInfusionDevicesRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_meta_v1_GetInfusionDevicesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_GetInfusionDevicesRequest_descriptor,
        new java.lang.String[] { "Page", "PageSize", "DeptId", });
    internal_static_meta_v1_GetInfusionDevicesResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_meta_v1_GetInfusionDevicesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_GetInfusionDevicesResponse_descriptor,
        new java.lang.String[] { "InfusionDevices", });
    internal_static_meta_v1_InfusionDeviceDetail_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_meta_v1_InfusionDeviceDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_InfusionDeviceDetail_descriptor,
        new java.lang.String[] { "BedNo", "Drugs", "Disease", "InfusionTime", "InfusionStatus", });
    internal_static_meta_v1_DrugDetail_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_meta_v1_DrugDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_DrugDetail_descriptor,
        new java.lang.String[] { "DrugId", "DrugName", });
    internal_static_meta_v1_GetUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_meta_v1_GetUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_GetUserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_meta_v1_GetUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_meta_v1_GetUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_GetUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_meta_v1_UserDetail_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_meta_v1_UserDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_meta_v1_UserDetail_descriptor,
        new java.lang.String[] { "UserId", "UserName", "UserRole", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
